server:
  port: 8761
spring:
  application:
      name:eureka
logging:
    level:
        org.springframework.web: 'ERROR'
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
