server:
    port: 8090
spring:
    application:
        name: crearnotificacion
    data:
        mongodb.uri: mongodb://w963363D.ad.bbva.com:27017/dbTaller        
eureka:
 instance:
   vipAddress: crearnotificacion
   virtualHostName: crearnotificacion
   leaseRenewalIntervalInSeconds: 1
   leaseExpirationDurationInSeconds: 2
 client:
    ServiceUrl:
       defaultZone: http://localhost:8762/eureka/

